CC=g++
CFLAGS=-static-libstdc++ -static-libgcc
SOURCES=Source/main.cpp Source/atom.cpp Source/data.cpp Source/ioManager.cpp Source/list.cpp Source/listhandler.cpp Source/node.cpp Source/parser.cpp
EXECUTABLE=lab2

all: 
	$(CC) $(CFLAGS) $(SOURCES) -o lab2

